### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by TheDiego845** [PABLO-1610/esx_airplanedealer#1]
Plane sql list?

**Comment by PABLO-1610** [comment]
You can find some [airplane list here](https://wiki.altv.mp/wiki/GTA:Vehicle_Models#PLANE)

You can convert to SQL if you want to.

**Comment by TheDiego845** [comment]
Ok and do you know how I can add an airport more the main airport?

**Comment by PABLO-1610** [comment]
No sorry
